[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 10000
verbosity = 3

[dependencies]
forge-std = "1.14.0"
"@openzeppelin-contracts" = "5.6.1"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
